version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api

  postgres:
    build: ./postgres
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - pg_data:/var/lib/postgresql/data
      - pg_wal_mnt:/mnt/server/archivedir

  api: &rails_api
    build:
      context: ./rails_api

    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_api:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  bundle:
  pg_wal_mnt:
  pg_data:
