

version: '3'
services:
  postgres:
    image: postgres:11.1
    volumes:
      - pg_data:/var/lib/postgresql/data

  api: &rails_api
    build:
      context: ./rails_api

    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_api:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  bundle:
  pg_data:
